no_worlds: 300
train_ratio: 0.7 #train ratio = 0.8*x
test_ratio: 0.2 #fixed
horizon: 8
n_action_steps: 4
n_obs_steps: 4
inspection_data : '/jackal_ws/src/mlda-barn-2024/inspection_data/kul_data_10Hz_done.csv'
dataset_script_src: '/jackal_ws/src/mlda-barn-2024/train_imitation/scripts/KULBarnDataset.py'
batch_size: 32
learning_rate: 0.00011
num_epochs: 80
save_loss_every: 300 #record train loss every x batch
validate_every: 10 #do val_loss every x epoch
patience: 5
dims_multiplier: 128 #base dim [2 , 4 , 8] * mul = 
diffusion_steps: 1000
suffix: 'diffuser_policy_10Hz_ddim'
num_inference_steps: 5      #reduce diffusion steps for inference
noise_scheduler: ddim

#Testing
model_path : '/jackal_ws/src/mlda-barn-2024/outputs/behavior_cloning_cnn/241219_133715/cnn_model.pth'