
inspection_data : '/jackal_ws/src/mlda-barn-2024/inspection_data/kul_data_10Hz_done.csv'
dataset_script_src: '/jackal_ws/src/mlda-barn-2024/train_imitation/dataset/KULBarnDataset.py'
train_ratio: 0.7 #train ratio = 0.8*x
batch_size: 32
learning_rate: 0.00001
num_epochs: 50
patience: 5
suffix: ''

#Testing
model_path : '/jackal_ws/src/mlda-barn-2024/outputs/behavior_cloning_cnn/241219_133715/cnn_model.pth'